### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by MamdMehrabi** [parchlinuxB/parch-iso-mate#1]
سلام و خسته نباشید؛
اول تشکر میکنم بابت اینکه قصد زنده کردن همچین دسکتاپ خوبی رو دارید 💙

و بریم سراغ اصل مطلب؛

توی عکس پایین میتونید ببینید که قصد چه کاری رو دارم

![image](https://github.com/parchlinuxB/parch-iso-mate/assets/121286220/8b85efb6-49b9-4839-8196-0885c28e307c)

و در نتیجه اروری که در نصب دریافت میکنم:

![image](https://github.com/parchlinuxB/parch-iso-mate/assets/121286220/dd9b3dd3-8560-47c5-bcb2-a01068781caa)

ممنون میشم کمک کنید (:

**Comment by AliAlmasi** [comment]
سلام. من مشکل شمارو خوندم، ولی دقیقا متوجه نمیشم که ممکنه به چه علت این مشکل رخ داده باشه.
من حدس میزنم که مشکل از پارچ و یا اینستالرش نیست، ولی بازم سعی میکنم با جستجو بفهمم که مشکل دقیقا کجاست.
لطفا اگر هرگونه لاگ از اینستالر دارید رو برای ما بصورت یک لینک pastebin ارسال کنید.

---

سهراب جان شما هم لطفا اگر امکانش هست یه نگاهی بنداز. ممنونم. @behdanisohrab

**Comment by behdanisohrab** [comment]
> سلام. من مشکل شمارو خوندم، ولی دقیقا متوجه نمیشم که ممکنه به چه علت این مشکل رخ داده باشه. من حدس میزنم که مشکل از پارچ و یا اینستالرش نیست، ولی بازم سعی میکنم با جستجو بفهمم که مشکل دقیقا کجاست. لطفا اگر هرگونه لاگ از اینستالر دارید رو برای ما بصورت یک لینک pastebin ارسال کنید.
> 
> سهراب جان شما هم لطفا اگر امکانش هست یه نگاهی بنداز. ممنونم. @behdanisohrab



احتمالا مشکل از دیسکشون باشه، رمزنگاری شده باشه یا هرچی

درضمن روی پارتیشن shrink شده هم نمیشه پارچ نصب کرد

**Comment by AliAlmasi** [comment]
> احتمالا مشکل از دیسکشون باشه، رمزنگاری شده باشه یا هرچی
> 
> درضمن روی پارتیشن shrink شده هم نمیشه پارچ نصب کرد

بله منم حدس میزدم مشکل از سمت کاربر باشه. @MamdMehrabi

**Comment by MamdMehrabi** [comment]
بالاخره راهی برای فیکس کردنش یافتم ( البته به کمک علی و سهراب )
خب وقتی توی ویندوز راهی برای درست کردن پارتیشن نباشه و ارور بده طبیعتا برای نصب لینوکس هم ارور میده...
برای همین اومدم و خلاصه هرجوری شده یه پارتیشن توی ویندوز ساختم و بعدش توی پارچ اونو سلکت کردم و مشکل برطرف شد...
